name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

    #  # Step 4: Download and Install Latest UPX
    #  - name: Download and Install UPX
    #    run: |
    #      # Fetch the latest release URL of UPX from GitHub API
    #      $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/upx/upx/releases/latest"
    #      $downloadUrl = $latestRelease.assets | Where-Object { $_.name -like "*win64.zip" } | Select-Object -ExpandProperty browser_download_url
    #      
    #      # Download and extract UPX
    #      Invoke-WebRequest -Uri $downloadUrl -OutFile upx.zip
    #      Expand-Archive -Path upx.zip -DestinationPath upx

    #      # Move UPX executable to main `upx` folder for easier access
    #      Move-Item -Path .\upx\*\upx.exe -Destination .\upx\upx.exe

      # Step 6: Build executable with Nuitka
      - name: Build executable with Nuitka
        run: |
          nuitka --standalone --plugin-enable=upx --assume-yes-for-downloads --onefile --windows-icon-from-ico=assets/appl.ico --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
          if (Test-Path "color_palette_creator.dist\\color_palette_creator.exe") {
              Move-Item -Path "color_palette_creator.dist\\color_palette_creator.exe" -Destination "."
          }

      # Step 7: Compress executable with UPX (optional)
      #- name: Compress executable with UPX
      #  if: success()
      #  run: |
      #    .\upx\upx.exe --best --lzma color_palette_creator.exe

      # Step 8: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            color_palette_creator.exe
            src/color_palette_creator.py
            requirements.txt