name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: .

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      # Step 4: Install UPX for compression (optional)
      - name: Install UPX
        run: choco install upx -y

      - name: Build executable with Nuitka
        run: |
          nuitka --standalone --onefile --windows-icon-from-ico=assets/appl.ico src/color_palette_analysis.py
          if (Test-Path "color_palette_analysis.dist\\color_palette_analysis.exe") {
              Move-Item -Path "color_palette_analysis.dist\\color_palette_analysis.exe" -Destination "."
            }

      # Step 6: Compress executable with UPX (optional)
      - name: Compress executable with UPX
        if: success()
        run: |
          upx --best --lzma color_palette_analysis.exe

      # Step 7: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            color_palette_analysis.exe
            src/color_palette_analysis.py
            requirements.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
