name: Update Requirements

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install pipreqs
      - name: Install pipreqs
        run: |
          pip install pipreqs

      # Step 4: Generate requirements.txt with pipreqs
      - name: Generate requirements.txt
        run: |
          pipreqs /github/workspace --force

      # Step 5: Commit updated requirements.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated requirements.txt"
