name: Update Requirements

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies and update requirements.txt
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || true
      - name: Update requirements.txt
        run: |
          pip freeze > requirements.txt

      # Step 4: Commit updated requirements.txt
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated requirements.txt"